# Generated by Django 3.2.13 on 2022-11-28 05:27

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('english_name', models.CharField(max_length=20)),
                ('back_number', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('team', models.CharField(max_length=20)),
                ('player_image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='')),
                ('position', models.CharField(max_length=10)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
    ]
