# Generated by Django 3.2.13 on 2022-12-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(max_length=10),
        ),
    ]
