# Generated by Django 3.2.13 on 2022-12-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korea', '0002_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='block_comment',
        ),
        migrations.AddField(
            model_name='block',
            name='block_comment',
            field=models.ManyToManyField(related_name='blok', to='korea.Comment'),
        ),
    ]
