# Generated by Django 3.2.13 on 2022-12-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korea', '0003_auto_20221206_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='block_comment',
            field=models.ManyToManyField(related_name='block', to='korea.Comment'),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
