# Generated by Django 3.2.13 on 2022-12-06 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('korea', '0004_auto_20221206_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='block_comment',
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_comment', models.ManyToManyField(related_name='blok', to='korea.Comment')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korea.comment')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korea.players')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
